name: educational_quiz_game
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  image_picker: ^1.1.2
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter_smart_dialog: ^4.9.8
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^5.3.0
  riverpod: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/eq_icon_t.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/eq_splash.png"
  android: true
  ios: false


#  dart run flutter_native_splash:create
#flutter pub run flutter_launcher_icons