// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAyqJjWK6VS_4SGKwiq1FkgrG700kkb8',
    appId: '1:800124498704:web:803d84331088f6dca26b95',
    messagingSenderId: '800124498704',
    projectId: 'educational-game-8a52e',
    authDomain: 'educational-game-8a52e.firebaseapp.com',
    storageBucket: 'educational-game-8a52e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6z4hRGA68nSYrTDwoWr2ZGMT55-WWW6M',
    appId: '1:800124498704:android:4c934f2fca48a9bea26b95',
    messagingSenderId: '800124498704',
    projectId: 'educational-game-8a52e',
    storageBucket: 'educational-game-8a52e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXCCCZGKhkwKPsb8SGWwPXRNReIZT-wsQ',
    appId: '1:800124498704:ios:0cfe5b87c25fc1aea26b95',
    messagingSenderId: '800124498704',
    projectId: 'educational-game-8a52e',
    storageBucket: 'educational-game-8a52e.appspot.com',
    iosBundleId: 'com.example.educationalQuizGame',
  );
}
